// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SHM_MS.DbContexts;

#nullable disable

namespace SHM_MS.Migrations
{
    [DbContext(typeof(SHMContext))]
    [Migration("20250604031535_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SHM_MS.Models.Report", b =>
                {
                    b.Property<Instant>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<int>("VmId")
                        .HasColumnType("integer")
                        .HasColumnName("vm_id");

                    b.Property<double>("CpuUsagePercent")
                        .HasColumnType("double precision")
                        .HasColumnName("cpu_usage_percent");

                    b.Property<double>("FreeMemory")
                        .HasColumnType("double precision")
                        .HasColumnName("free_memory");

                    b.Property<double>("FreeSpace")
                        .HasColumnType("double precision")
                        .HasColumnName("free_space");

                    b.Property<double>("TotalMemory")
                        .HasColumnType("double precision")
                        .HasColumnName("total_memory");

                    b.Property<double>("TotalSpace")
                        .HasColumnType("double precision")
                        .HasColumnName("total_space");

                    b.HasKey("Timestamp", "VmId")
                        .HasName("pk_reports");

                    b.HasIndex("VmId")
                        .HasDatabaseName("ix_reports_vm_id");

                    b.ToTable("reports", (string)null);
                });

            modelBuilder.Entity("SHM_MS.Models.Vm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_vms");

                    b.ToTable("vms", (string)null);
                });

            modelBuilder.Entity("SHM_MS.Models.Report", b =>
                {
                    b.HasOne("SHM_MS.Models.Vm", "Vm")
                        .WithMany("Reports")
                        .HasForeignKey("VmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reports_vms_vm_id");

                    b.Navigation("Vm");
                });

            modelBuilder.Entity("SHM_MS.Models.Vm", b =>
                {
                    b.Navigation("Reports");
                });
#pragma warning restore 612, 618
        }
    }
}
